import * as dotenv from "dotenv";
import * as path from "path";

dotenv.config({ path: path.resolve(process.cwd(), ".env.local") });

import { answerMerchantQuestion } from "../lib/ai/agent";
import {
  approveAction,
  rejectAction,
  createActionProposal,
  getRecentAgentActions,
} from "../lib/db/queries";

async function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

async function runTests() {
  console.log("==================================================");
  console.log("?? Testing Phase 5: Controlled Agentic Actions & Human Approval");
  console.log("==================================================\n");

  // ----------------------------------------------------------------
  // TEST 1: Agent creates a recovery plan proposal (NO direct execution)
  // ----------------------------------------------------------------
  console.log("--------------------------------------------------");
  console.log("[TEST 1] AI Prompt: 'Prepare a recovery plan for customers with repeated payment failures.'");
  console.log("--------------------------------------------------");

  const res1 = await answerMerchantQuestion(
    "Prepare a recovery plan for customers with repeated payment failures."
  );

  console.log(`??? Tools Used: ${JSON.stringify(res1.toolsUsed)}`);
  console.log(`?? Action Proposal ID: ${res1.actionProposal?.id}`);
  console.log(`?? Action Title: ${res1.actionProposal?.title}`);
  console.log(`?? Action Status: ${res1.actionProposal?.status}`);
  console.log(`?? Agent Answer:\n${res1.answer.slice(0, 250)}...\n`);

  if (!res1.actionProposal) {
    throw new Error("TEST 1 FAILED: No action proposal was generated by the agent!");
  }

  if (res1.actionProposal.status !== "PENDING_APPROVAL") {
    throw new Error(`TEST 1 FAILED: Status is not PENDING_APPROVAL: ${res1.actionProposal.status}`);
  }

  const actionId1 = res1.actionProposal.id;

  // ----------------------------------------------------------------
  // TEST 2: Human approves the recovery plan
  // ----------------------------------------------------------------
  console.log("--------------------------------------------------");
  console.log(`[TEST 2] Operator approves recovery plan: ${actionId1}`);
  console.log("--------------------------------------------------");

  const approveRes1 = await approveAction(actionId1);
  console.log(`? Approved Status: ${approveRes1.action.status}`);
  console.log(`? Execution Result: ${JSON.stringify(approveRes1.executionResult)}`);
  console.log(`? Execution Message: ${approveRes1.message}`);

  if (approveRes1.action.status !== "EXECUTED") {
    throw new Error(`TEST 2 FAILED: Expected EXECUTED but got ${approveRes1.action.status}`);
  }

  // ----------------------------------------------------------------
  // TEST 3: Duplicate approval attempt (Idempotency protection)
  // ----------------------------------------------------------------
  console.log("--------------------------------------------------");
  console.log(`[TEST 3] Duplicate approval attempt on already executed action: ${actionId1}`);
  console.log("--------------------------------------------------");

  try {
    await approveAction(actionId1);
    throw new Error("TEST 3 FAILED: Duplicate approval did not throw!");
  } catch (err: unknown) {
    console.log(`??? Idempotency guard triggered as expected: "${err instanceof Error ? err.message : err}"`);
  }

  // ----------------------------------------------------------------
  // TEST 4: Prepare a support case proposal and reject it
  // ----------------------------------------------------------------
  console.log("--------------------------------------------------");
  console.log("[TEST 4 & 5] AI Prompt: 'Create a support case for the UPI degradation.'");
  console.log("--------------------------------------------------");

  await sleep(2000); // cooldown

  const res2 = await answerMerchantQuestion(
    "Create a support case for the UPI degradation."
  );

  console.log(`??? Tools Used: ${JSON.stringify(res2.toolsUsed)}`);
  console.log(`?? Action Proposal ID: ${res2.actionProposal?.id}`);
  console.log(`?? Action Title: ${res2.actionProposal?.title}`);
  console.log(`?? Action Status: ${res2.actionProposal?.status}`);

  if (!res2.actionProposal) {
    throw new Error("TEST 4 FAILED: Support case proposal was not generated!");
  }

  const actionId2 = res2.actionProposal.id;

  // Operator rejects action
  console.log(`\nOperator rejects support case action: ${actionId2}`);
  const rejectRes2 = await rejectAction(actionId2, "Merchant operator decided not to escalate to bank partners.");
  console.log(`? Rejection Status: ${rejectRes2.status}`);
  console.log(`? Rejection Result: ${JSON.stringify(rejectRes2.result)}`);

  if (rejectRes2.status !== "REJECTED") {
    throw new Error(`TEST 5 FAILED: Expected REJECTED but got ${rejectRes2.status}`);
  }

  // ----------------------------------------------------------------
  // TEST 6: Prepare a refund proposal for pay_000001
  // ----------------------------------------------------------------
  console.log("--------------------------------------------------");
  console.log("[TEST 6] AI Prompt: 'Prepare a refund for payment pay_000001 due to duplicate charge.'");
  console.log("--------------------------------------------------");

  await sleep(2000); // cooldown

  const res3 = await answerMerchantQuestion(
    "Prepare a refund for payment pay_000001 due to duplicate charge."
  );

  console.log(`??? Tools Used: ${JSON.stringify(res3.toolsUsed)}`);
  console.log(`?? Action Proposal ID: ${res3.actionProposal?.id}`);
  console.log(`?? Action Title: ${res3.actionProposal?.title}`);
  console.log(`?? Action Target: ${res3.actionProposal?.target_id}`);
  console.log(`?? Policy Sources: ${JSON.stringify(res3.actionProposal?.policy_sources)}`);

  if (!res3.actionProposal) {
    throw new Error("TEST 6 FAILED: Refund proposal was not generated!");
  }

  const actionId3 = res3.actionProposal.id;

  // Operator approves refund
  const approveRes3 = await approveAction(actionId3);
  console.log(`? Approved Refund Status: ${approveRes3.action.status}`);
  console.log(`? Simulated Execution Notice: ${JSON.stringify(approveRes3.executionResult)}`);

  // ----------------------------------------------------------------
  // TEST 7: Security validation tests
  // ----------------------------------------------------------------
  console.log("--------------------------------------------------");
  console.log("[TEST 7 & 8] Security Guardrail Tests");
  console.log("--------------------------------------------------");

  // Test nonexistent ID
  try {
    await approveAction("non_existent_id_9999");
    throw new Error("Failed security test: Approved non-existent action!");
  } catch (err: unknown) {
    console.log(`??? Non-existent action rejection: "${err instanceof Error ? err.message : err}"`);
  }

  // Test invalid action type creation
  try {
    await createActionProposal({
      // @ts-expect-error Testing invalid action type
      actionType: "EXECUTE_ARBITRARY_SQL",
      title: "Malicious SQL",
      description: "DROP TABLE payments",
      parameters: {},
    });
  } catch (err: unknown) {
    console.log(`??? Invalid action type blocked: "${err instanceof Error ? err.message : err}"`);
  }

  // Verify Audit Log retrieval
  const auditLog = await getRecentAgentActions(5);
  console.log(`\n?? Recent Audit Trail Entries (${auditLog.length} recorded):`);
  auditLog.forEach((act, i) => {
    console.log(`   ${i + 1}. [${act.status}] ${act.action_type}: "${act.title}"`);
  });

  console.log("\n==================================================");
  console.log("? All Phase 5 action tests passed successfully!");
  console.log("==================================================");
}

runTests().catch(console.error);
